### ISSUE TITLE
Funcionamento do Perga ..

### ISSUE THREAD

**Issue by mazarafa** [northy/PergaBot#2]
Caramba brother, adorei essa funcionalidade do teu código Mas ele funciona apenas para livros ou para outras coisas (tipo renovar livros de outras instituição tbm) ?

**Comment by northy** [comment]
Existe a chance de ele funcionar sim, alterando o link de acesso do pergamum (já que o sistema provavelmente é o mesmo), porém não tenho como garantir, já que não tenho acesso a nenhum para testar.

**Comment by mazarafa** [comment]
eu tentei na biblioteca municipal de cbá, e funcionou pela informação que me disse, apenas troquei o link. E meio que funcionou pra renovar um livro apenas, logo veio um aviso no email da minha mãe (como se tive alguém hackeando o usuario dela) hasuhaushsa
Mas Northy, parabéns. Gostei do Perga namoralzinha

**Comment by northy** [comment]
O e-mail pode ter sido por utilizar requests, talvez o header fez o sistema pensar que era um ataque hauhaauhau, mas obrigado :)
